add adjustments to the repository readme
PEM-Humboldt/.github pull request #318
Opened 2024-02-21 19:47 UTC by hacheG

## 🛠️ Changes
add adjustments to readme.
add images.
add videos.
switch languaje to spanish.

## 📝 Associated issues
#38 

## 🤔 Considerations
none

2024-02-22 15:44 UTC, erikasv commented on README.md
> +- [Plantilla para llaves ssh](acerca_de_llaves_SSH(ssh_keys).md) -> esta clave es necesaria para una mejor seguridad al momento de envia codigo al remoto
Esto no es una plantilla, puedes dejarle simplemente `Llaves SSH`.

2024-02-22 15:46 UTC, erikasv commented on README.md
> +- [Plantilla para proyectos de software](readme_template.md) -> Al momento de iniciar un proyecto completo
a estos dos es mejor ponerle que son plantillas del readme y al segundo depronto "aplicaciones" en logar de proyectos.

Ya sea acá en un títulito para los dos, o dentro de cada plantilla, agregar en la sección de la licencia que por lo regular se debe incluir un archivo dedicado para la licencia, en lugar de un enlace como está en la plantilla

2024-02-23 18:27 UTC, cazapatamar reviewed
Si lo consideran, dejo algunas sugerencias mas de forma. Me parece que la parte de configuracion de git y las llaves queda muy escondido por lo que creo que podria tener una seccion propia mas arriba. Tambien me parece mejor separar la seccion de plantilas de los recursos. Sugiero una estructura puede ser así:

# Manejo de repositorios y tips para el uso de GIT
## Instalar GIT
### Para usuarios de windows
### Usuarios Mac OS y Linux
## Configurar GIT
- Aca lo que se tiene de configuracion inicial y el global
- Aliases (Opcional)
- Llaves SSH
## Recursos
-  Libro para aprender GIT
- Otros
## Plantillas
- Scripts
- Aplicaciones

2024-02-24 16:32 UTC, erikasv commented
Estoy de acuerdo con la sugerencia de @cazapatamar , @hacheG por favor reorganizar el readme principal así

2024-02-27 20:57 UTC, erikasv approved these changes

2024-02-28 01:49 UTC, cazapatamar requested changes

2024-02-28 01:49 UTC, cazapatamar commented on configuracion_aliases.md
> +En Git solemos repetir comandos con regualridad, asi que si se desea usar un metodo mnemotecnico, es apropiado usar los alias
Arreglar typo "regularidad"

2024-02-28 12:42 UTC, cazapatamar approved these changes

2024-02-28 15:29 UTC, merged